FROM centos:7
RUN echo "" >> /etc/profile
RUN yum -y install httpd php
 
COPY test.php /var/www/html/

ENV PATH $PATH:/usr/local/scala/scala-2.11.7/bin
ENTRYPOINT exec_entry p1_entry
CMD  exec_cmd p1_cmd